# Generated by Django 3.0.8 on 2020-07-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='student',
        ),
    ]
